# Generated by Django 3.2 on 2024-07-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preventista',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del proveedor')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio del proveedor')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad del proveedor')),
                ('rubro', models.CharField(max_length=50, verbose_name='Rubro del proveedor')),
            ],
            options={
                'verbose_name': 'Preventista',
                'verbose_name_plural': 'Preventistas',
            },
        ),
    ]
