# Generated by Django 3.2 on 2024-07-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preventistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventista',
            old_name='id',
            new_name='identificador',
        ),
    ]
