# Generated by Django 3.2 on 2024-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_Producto',
            field=models.ImageField(blank=True, upload_to='Cliente', verbose_name='avatar'),
        ),
    ]
